DROP TABLE IF EXISTS ai_run;
DROP TABLE IF EXISTS audit_log;
DROP TABLE IF EXISTS release_event;
DROP TABLE IF EXISTS incident;
DROP TABLE IF EXISTS rollback_record;
DROP TABLE IF EXISTS approval;
DROP TABLE IF EXISTS release;
DROP TABLE IF EXISTS alert_rule;
DROP TABLE IF EXISTS metric_panel;
DROP TABLE IF EXISTS log_source;
DROP TABLE IF EXISTS certificate;
DROP TABLE IF EXISTS domain;
DROP TABLE IF EXISTS environment;
DROP TABLE IF EXISTS build;
DROP TABLE IF EXISTS pipeline;
DROP TABLE IF EXISTS repo;
DROP TABLE IF EXISTS service;

